# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 527d4e3d39f68f34e341651699feca0e0093d04cebf82d24f9aa304a6b4f7aa9915c8a9e18b9a6d678b29c7e2e180dbf749bed4078f60331d61ffe14591f6f7f

test:
  secret_key_base: 81f3941442d74e4fdeead4bc31845c82e3e124dd069cc33783db796cdb4f7998efad087f272f1f3c5e0c8f70d69a175643fd73d1622234609eb62351cc759b29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
